name: Build & Deploy to EC2 (Docker)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub (with password)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy container
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop github-crawler || true
            docker rm github-crawler || true
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/github-crawler:latest
            docker run -d --name github-crawler -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/github-crawler:latest
          EOF
