name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 to known hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Copy project files to EC2
        run: |
          rsync -avz --exclude='.git' ./ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/my-fastapi-app/

      - name: Deploy on EC2 with Docker Compose
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/my-fastapi-app
            docker-compose down
            docker-compose up -d --build
          EOF
